name: Check-Build

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x' ]

    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: true
          
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore and build (publish)
        run: msbuild /restore /p:Platform=x64 /p:PlatformTarget=x64 /p:Configuration=Release /p:RuntimeIdentifier=win-x64 /t:Publish /p:PublishProfile=plugin_PSMoveService\Properties\PublishProfiles\FolderProfile.pubxml

      - name: Pack published files
        run: |
          cd plugin_PSMoveService/bin/Release/net8.0/win-x64/publish
          7z a plugin_PSMoveService.zip *
        
      - name: Upload plugin artifact
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "plugin_PSMoveService Build Artifact"
          files: |
            ./plugin_PSMoveService/bin/Release/net8.0/win-x64/publish/plugin_PSMoveService.zip
            ./external/manifest.json